//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockSurvey
    {
        public int BlockId { get; set; }
        public int SurveyId { get; set; }
        public string Name { get; set; }
    
        public virtual Block Block { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
