//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public House()
        {
            this.Receipts = new HashSet<Receipt>();
            this.Users = new HashSet<User>();
            this.HelpdeskRequests = new HashSet<HelpdeskRequest>();
        }
    
        public int Id { get; set; }
        public Nullable<int> BlockId { get; set; }
        public string Floor { get; set; }
        public string HouseName { get; set; }
        public string Description { get; set; }
        public Nullable<double> Area { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public string ProfileImage { get; set; }
        public string CoverImage { get; set; }
        public Nullable<bool> DisplayMember { get; set; }
        public Nullable<bool> AllowOtherView { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> WaterMeter { get; set; }
    
        public virtual Block Block { get; set; }
        public virtual HouseCategory HouseCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HelpdeskRequest> HelpdeskRequests { get; set; }
    }
}
