//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int id { get; set; }
        public string originalUrl { get; set; }
        public string url { get; set; }
        public string thumbnailUrl { get; set; }
        public string userCropUrl { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> postId { get; set; }
    }
}
