//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationChange
    {
        public int ID { get; set; }
        public int NotificationObjectID { get; set; }
        public string Verb { get; set; }
        public int Actor { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual NotificationObject NotificationObject { get; set; }
        public virtual User User { get; set; }
    }
}
