//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingMemberRequest
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<long> CreateDate { get; set; }
        public Nullable<long> CloseDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> HouseholderId { get; set; }
        public Nullable<int> PendingUserId { get; set; }
        public Nullable<int> ManagerId { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
