//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricesOfUtilityServiceCat
    {
        public int Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Name { get; set; }
        public Nullable<double> FromAmount { get; set; }
        public Nullable<double> ToAmount { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual UtilityServiceCategory UtilityServiceCategory { get; set; }
    }
}
