//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptDetail
    {
        public int Id { get; set; }
        public Nullable<double> TotalBill { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Unit { get; set; }
        public Nullable<int> ServiceFeeId { get; set; }
        public Nullable<int> ReceiptId { get; set; }
    
        public virtual Receipt Receipt { get; set; }
        public virtual ServiceFee ServiceFee { get; set; }
    }
}
