//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAnswerSurvey
    {
        public int Id { get; set; }
        public Nullable<int> SurveyId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AnswerId { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Survey Survey { get; set; }
        public virtual User User { get; set; }
    }
}
