//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReportPost
    {
        public int UserId { get; set; }
        public int PostId { get; set; }
        public int ReportId { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual Report Report { get; set; }
        public virtual User User { get; set; }
    }
}
